# fly.toml app configuration file generated for hannah-kofman on 2024-01-28T21:29:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hannah-kofman'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
